#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CERN.
#
# inv-test is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

set -e

SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
PROGRAM=`basename $0`

source "${SCRIPT_DIR}/includes/message.sh"

# Displays program name
msg "PROGRAM: ${PROGRAM}"

# poetry is a mandatory condition to launch this program!
if [[ -z "${VIRTUAL_ENV}" ]]; then
  error_msg+exit "Error - Launch this script via poetry command:\n\tpoetry run ${PROGRAM}"
fi

if [[ -z "${FLASK_DEBUG}" ]]; then
  export FLASK_DEBUG=True
fi
if [[ -z "${FLASK_ENV}" ]]; then
  export FLASK_ENV="development"
fi

CELERY_LOG_LEVEL="INFO"
worker=true
while test $# -gt 0
do
  case "$1" in
    -l|--loglevel)
      CELERY_LOG_LEVEL=$2
      shift ;;
    -n|--no-worker)
      worker=false ;;
    (--) shift; break;;
    (*) break;;
  esac
  shift
done

# Start Worker and Server
if $worker; then
  celery -A invenio_app.celery worker -l ${CELERY_LOG_LEVEL} --beat & pid_celery=$!
fi

invenio run \
       --cert "$SCRIPT_DIR"/../docker/nginx/test.crt \
       --key "$SCRIPT_DIR"/../docker/nginx/test.key & pid_server=$!

trap 'kill $pid_celery $pid_server &>/dev/null' EXIT

wait $pid_celery $pid_server
